FROM arm32v7/python:2-slim

RUN apt-get update && apt-get install build-essential -y --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN python -m pip install --upgrade pip setuptools wheel Adafruit_DHT requests
WORKDIR /app
COPY AdafruitDHT.py /app
RUN chmod +x AdafruitDHT.py
CMD [ "./AdafruitDHT.py" ]
